// Generates crawlable copies of index.html for each route, plus sitemap.xml, feed.xml,
// social share cards and app icons. Run after any change to index.html or posts/:
//   node scripts/build.mjs
// No dependencies. Content comes from the POSTS array in index.html's x-dc script block;
// posts with `md: true` take their body from posts/<id>.md (see scripts/markdown.mjs).
// Share cards and icons are rendered with headless Chrome (CHROME_PATH, default: the macOS app);
// without Chrome the build still succeeds and reuses existing images.
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import vm from 'node:vm';
import { markdownToHtml } from './markdown.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://kellock.com.au';
const MARK = '<!-- GENERATED by scripts/build.mjs from index.html. Do not edit; edit index.html and rebuild. -->';
const CHROME = process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';

let src = readFileSync(join(ROOT, 'index.html'), 'utf8');

// Evaluate the x-dc script with just enough stubs to read its constants.
const script = src.match(/<script type="text\/x-dc"[^>]*>([\s\S]*?)<\/script>/)[1];
const ctx = { DCLogic: class {}, window: { location: { hash: '', pathname: '/' } }, localStorage: { getItem: () => null, setItem() {} } };
vm.createContext(ctx);
vm.runInContext(script + '\n;globalThis.__out = { POSTS, HOME_TITLE, HOME_DESC, WRITING_TITLE, WRITING_DESC, ABOUT_TITLE, ABOUT_DESC, ABOUT_TAGLINE, ABOUT_UPDATED, HEADLINE, TAGLINE, HOME_ABOUT, SOCIALS, BIO, JOBS, FOCUS, CREDENTIALS, SKILLS, BOARD, SPEAKING, CONTACT_NOTE, WRITING_INTRO };', ctx);
const { POSTS, HOME_TITLE, HOME_DESC, WRITING_TITLE, WRITING_DESC, ABOUT_TITLE, ABOUT_DESC, ABOUT_TAGLINE, ABOUT_UPDATED, HEADLINE, TAGLINE, HOME_ABOUT, SOCIALS, BIO, JOBS, FOCUS, CREDENTIALS, SKILLS, BOARD, SPEAKING, CONTACT_NOTE, WRITING_INTRO } = ctx.__out;
for (const p of POSTS) if (p.related && !POSTS.some(x => x.id === p.related)) throw new Error(`POSTS: ${p.id} relates to unknown post ${p.related}`);

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const ld = obj => '<script type="application/ld+json">\n' + JSON.stringify({ '@context': 'https://schema.org', ...obj }, null, 2).replace(/</g, '\\u003c') + '\n</script>';
const sameAs = SOCIALS.filter(s => /^https?:/.test(s.href)).map(s => s.href);
// One WebSite and one Person node on every page; other nodes reference them by @id.
const person = { '@type': 'Person', '@id': SITE + '/#person' };
const website = { '@type': 'WebSite', '@id': SITE + '/#website' };
const WEBSITE_NODE = { ...website, name: 'Matt Kellock', url: SITE + '/', inLanguage: 'en-AU', publisher: person };
const personNode = image => ({
  ...person, name: 'Matt Kellock', honorificSuffix: 'AACS CP',
  jobTitle: 'Technology leader: platform engineering, security and governance',
  description: TAGLINE, url: SITE + '/about/', image: imageLd(image), email: 'mailto:matt@kellock.com.au', sameAs,
  address: { '@type': 'PostalAddress', addressLocality: 'Melbourne', addressRegion: 'Victoria', addressCountry: 'AU' },
  alumniOf: { '@type': 'CollegeOrUniversity', name: 'RMIT University' },
  memberOf: { '@type': 'Organization', name: 'Australian Computer Society' },
  hasCredential: [
    { '@type': 'EducationalOccupationalCredential', name: 'Certified Professional (AACS CP)', recognizedBy: { '@type': 'Organization', name: 'Australian Computer Society' } },
    { '@type': 'EducationalOccupationalCredential', name: 'Bachelor of Information Technology', recognizedBy: { '@type': 'CollegeOrUniversity', name: 'RMIT University' } }
  ],
  knowsAbout: ['Platform engineering', 'DevSecOps', 'ISO 27001', 'Cloud migration', 'M&A technology integration', 'Technology governance', 'AI governance', 'Technology risk and audit']
});
const graph = (...nodes) => ld({ '@graph': [WEBSITE_NODE, personNode(PORTRAIT), ...nodes] });
const crumbs = items => ({ '@type': 'BreadcrumbList', itemListElement: items.map(([name, path], i) => ({ '@type': 'ListItem', position: i + 1, name, item: SITE + path })) });

function write(rel, content) {
  const file = join(ROOT, rel);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
  console.log('wrote', rel);
}

// ---- Dates: posts carry a date only; publish time is 09:00 Melbourne time. ----
const melOffset = dt => {
  const name = new Intl.DateTimeFormat('en-AU', { timeZone: 'Australia/Melbourne', timeZoneName: 'longOffset' })
    .formatToParts(new Date(dt + 'T12:00:00Z')).find(p => p.type === 'timeZoneName').value;
  return name.replace('GMT', '') || '+00:00';
};
const isoTime = dt => `${dt}T09:00:00${melOffset(dt)}`;
const rfc822 = dt => {
  const [y, m, d] = dt.split('-').map(Number);
  const day = new Date(Date.UTC(y, m - 1, d));
  const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${days[day.getUTCDay()]}, ${String(d).padStart(2, '0')} ${months[m - 1]} ${y} 09:00:00 ${melOffset(dt).replace(':', '')}`;
};
const readMins = words => Math.max(1, Math.round(words / 230));

// ---- Images: pixel size from the PNG or JPEG header (for og:image:width/height). ----
function imageSize(rel) {
  const b = readFileSync(join(ROOT, rel));
  if (b.readUInt32BE(0) === 0x89504e47) return { width: b.readUInt32BE(16), height: b.readUInt32BE(20), type: 'image/png' };
  for (let i = 2; i < b.length - 9;) {
    const marker = b[i + 1], len = b.readUInt16BE(i + 2);
    if (marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker)) {
      return { width: b.readUInt16BE(i + 7), height: b.readUInt16BE(i + 5), type: 'image/jpeg' };
    }
    i += 2 + len;
  }
  return null;
}
const imageFor = (rel, alt) => ({ url: SITE + rel, alt, ...(imageSize(rel) || {}) });
const imageLd = image => ({ '@type': 'ImageObject', url: image.url, ...(image.width ? { width: image.width, height: image.height } : {}) });

// ---- Headless Chrome ----
const hasChrome = existsSync(CHROME);
// PLAYWRIGHT_MODULE (a path to an installed playwright package) renders with Playwright instead of Chrome's
// --screenshot, which clips the bottom of the page in some headless builds.
const playwright = process.env.PLAYWRIGHT_MODULE ? (await import(process.env.PLAYWRIGHT_MODULE)).default ?? (await import(process.env.PLAYWRIGHT_MODULE)) : null;
async function screenshot(url, out, width, height, scale) {
  if (!hasChrome && !playwright) return false;
  mkdirSync(dirname(join(ROOT, out)), { recursive: true });
  if (playwright) {
    const browser = await playwright.chromium.launch({ executablePath: hasChrome ? CHROME : undefined, args: (process.env.CHROME_FLAGS || '').split(' ').filter(Boolean) });
    try {
      const page = await browser.newPage({ viewport: { width, height }, deviceScaleFactor: scale });
      await page.goto(url, { waitUntil: 'networkidle' });
      await page.evaluate(() => document.fonts.ready);
      await page.waitForTimeout(300);
      await page.screenshot({ path: join(ROOT, out) });
    } catch (e) { console.warn('warning: playwright render failed:', e.message); } finally { await browser.close(); }
  } else
  // CHROME_FLAGS adds flags, e.g. "--no-sandbox --ignore-certificate-errors" when rendering as root behind a TLS-inspecting proxy.
  spawnSync(CHROME, [...(process.env.CHROME_FLAGS || '').split(' ').filter(Boolean), '--headless=new', '--disable-gpu', '--hide-scrollbars', `--force-device-scale-factor=${scale}`,
    `--window-size=${width},${height}`, '--virtual-time-budget=10000', `--screenshot=${join(ROOT, out)}`, url], { stdio: 'ignore', timeout: 60000 });
  const size = existsSync(join(ROOT, out)) && imageSize(out);
  if (size && size.width === width * scale && size.height === height * scale) return true;
  if (existsSync(join(ROOT, out))) rmSync(join(ROOT, out));
  return false;
}

// ---- Share cards: images/cards/<key>-<hash>.png, re-rendered only when their content changes. ----
const CARD_DIR = 'images/cards';
const cardTemplate = join(ROOT, 'scripts/card-template.html');
const cardVersion = createHash('sha256').update('1x').update(readFileSync(cardTemplate)).update(readFileSync(join(ROOT, 'images/portrait.jpg'))).digest('hex');
const usedCards = new Set();
const PORTRAIT = imageFor('/images/portrait.jpg', 'Portrait of Matt Kellock');
const FALLBACK = PORTRAIT;
async function card(key, data, alt) {
  const hash = createHash('sha256').update(cardVersion + JSON.stringify(data)).digest('hex').slice(0, 8);
  let rel = `/${CARD_DIR}/${key}-${hash}.png`;
  if (!existsSync(join(ROOT, rel))) {
    const url = pathToFileURL(cardTemplate).href + '#' + Buffer.from(JSON.stringify(data)).toString('base64');
    if (await screenshot(url, rel.slice(1), 1200, 630, 1)) console.log('rendered', rel.slice(1));
    else {
      // No Chrome or the render failed: keep the previous card for this key if there is one.
      const prev = existsSync(join(ROOT, CARD_DIR)) && readdirSync(join(ROOT, CARD_DIR)).find(f => f.startsWith(key + '-') && f.endsWith('.png'));
      console.warn(`warning: could not render share card "${key}"${prev ? ', reusing ' + prev : ', using portrait.jpg'}`);
      if (!prev) return FALLBACK;
      rel = `/${CARD_DIR}/${prev}`;
    }
  }
  usedCards.add(rel.split('/').pop());
  return imageFor(rel, alt);
}
const eyebrow = p => [p.type, p.date, p.venue].filter(Boolean).join(' · ');
const siteCard = await card('site', { kind: 'site', eyebrow: 'Melbourne, Australia · AACS CP', title: 'Matt Kellock', headline: HEADLINE, dek: TAGLINE },
  'Matt Kellock: ' + HEADLINE);
const postImage = async p => p.image
  ? imageFor(p.image, p.imageAlt || p.title)
  : await card(p.id, { kind: 'post', eyebrow: eyebrow(p), title: p.title, dek: p.dek }, `${p.title}, by Matt Kellock`);

// ---- App icons from favicon.svg (rendered once; delete the PNGs to regenerate) ----
const iconPage = pathToFileURL(join(ROOT, 'scripts/icon-template.html')).href;
for (const [file, px] of [['apple-touch-icon.png', 180], ['icon-192.png', 192], ['icon-512.png', 512]]) {
  if (!existsSync(join(ROOT, file)) && await screenshot(iconPage, file, px, px, 1)) console.log('rendered', file);
}

const slug = t => t.toLowerCase().replace(/[&<>"]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const block = (b, id) => b.isH ? `<h2 id="${id}-${slug(b.text)}">${esc(b.text)}</h2>` : b.isQ ? `<blockquote>${esc(b.text)}</blockquote>` : `<p>${esc(b.text)}</p>`;
// Figure images with a sibling "<name>-light.<ext>" get a light-theme variant, and their intrinsic size.
const lightSrc = s => {
  const light = s.replace(/(\.\w+)$/, '-light$1');
  return s.startsWith('/') && existsSync(join(ROOT, light)) ? light : null;
};
const figureSize = s => s.startsWith('/') && existsSync(join(ROOT, s)) ? imageSize(s) : null;

// Markdown posts are converted once; the result feeds body.html, the static copy, the feed and the word counts.
const converted = new Map();
for (const p of POSTS) {
  if (p.md) {
    const md = readFileSync(join(ROOT, 'posts', p.id + '.md'), 'utf8');
    const expect = new Date(isoTime(p.updated || p.dt)).toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'Australia/Melbourne' });
    const shown = md.match(/Last updated (\d{1,2} [A-Z][a-z]+ \d{4})/);
    if (shown && shown[1] !== expect) throw new Error(`posts/${p.id}.md says "Last updated ${shown[1]}" but POSTS gives ${expect} (updated || dt)`);
    converted.set(p.id, markdownToHtml(md, p.id, { lightSrc, imageSize: figureSize }));
  } else {
    converted.set(p.id, { html: p.body.map(b => block(b, p.id)).join('\n'), words: p.body.map(b => b.text).join(' ').split(/\s+/).filter(Boolean).length, headings: [] });
  }
}
// Reading time per post, published in every page head for the app to show.
const readMap = Object.fromEntries(POSTS.map(p => [p.id, readMins(converted.get(p.id).words)]));
const readScript = `<script type="application/json" id="mk-read">${JSON.stringify(readMap)}</script>`;
// A contents list for long Markdown posts (four or more sections), inserted before the first section heading.
const tocFor = (p, c) => {
  const items = c.headings.filter(h => h.text !== 'References');
  if (!p.md || items.length < 4) return c.html;
  const toc = `<nav class="mk-toc" aria-labelledby="${p.id}-toc-h"><h2 id="${p.id}-toc-h">Contents</h2><ul>${items.map(h => `<li><a href="#${h.id}">${esc(h.text)}</a></li>`).join('')}</ul></nav>`;
  const i = c.html.indexOf('<h2 ');
  return i < 0 ? c.html : c.html.slice(0, i) + toc + '\n' + c.html.slice(i);
};

// ---- <head> metadata ----
function seoHead({ title, ogTitle = title, desc, path, type = 'website', robots = 'index, follow, max-image-preview:large, max-snippet:-1', image = siteCard, extra = [] }) {
  const url = SITE + path;
  return [
    `<title>${esc(title)}</title>`,
    `<meta name="description" content="${esc(desc)}">`,
    `<meta name="robots" content="${robots}">`,
    `<link rel="canonical" href="${url}">`,
    `<meta property="og:type" content="${type}">`,
    `<meta property="og:url" content="${url}">`,
    `<meta property="og:title" content="${esc(ogTitle)}">`,
    `<meta property="og:description" content="${esc(desc)}">`,
    `<meta property="og:image" content="${image.url}">`,
    image.type && `<meta property="og:image:type" content="${image.type}">`,
    image.width && `<meta property="og:image:width" content="${image.width}">`,
    image.height && `<meta property="og:image:height" content="${image.height}">`,
    `<meta property="og:image:alt" content="${esc(image.alt)}">`,
    `<meta name="twitter:title" content="${esc(ogTitle)}">`,
    `<meta name="twitter:description" content="${esc(desc)}">`,
    `<meta name="twitter:image" content="${image.url}">`,
    `<meta name="twitter:image:alt" content="${esc(image.alt)}">`,
    ...extra,
    readScript
  ].filter(Boolean).join('\n');
}

// The no-JavaScript copy of a page sits between <!-- noscript:start --> and <!-- noscript:end --> at the top of <body>.
const noscriptSlot = (noscript = '', extraBody = '') =>
  `<!-- noscript:start -->\n${noscript ? `<noscript>\n${noscript}\n</noscript>\n` : ''}${extraBody}<!-- noscript:end -->`;
function render({ head, jsonld = '', noscript = '', extraBody = '' }) {
  return src
    // Replacer functions, so '$' sequences in content ($$, $&, $') are inserted literally.
    .replace(/<!-- seo:start -->[\s\S]*?<!-- seo:end -->/, () => `<!-- seo:start -->\n${head}\n<!-- seo:end -->`)
    .replace(/<!-- seo-ld:start -->[\s\S]*?<!-- seo-ld:end -->/, () => `<!-- seo-ld:start -->${jsonld ? '\n' + jsonld + '\n' : ''}<!-- seo-ld:end -->`)
    .replace(/<!-- noscript:start -->[\s\S]*?<!-- noscript:end -->/, () => noscriptSlot(noscript, extraBody))
    .replace(/^<!DOCTYPE html>\n/i, () => `<!DOCTYPE html>\n${MARK}\n`);
}

const nav = `<nav><a href="/">Matt Kellock</a> · <a href="/writing/">Writing</a> · <a href="/about/">About</a> · <a href="/feed.xml">RSS</a></nav>`;
const listing = POSTS.map(p => `<li><a href="/writing/${p.id}/">${esc(p.title)}</a> (${esc(p.type)}, <time datetime="${p.dt}">${esc(p.date)}</time>${p.audience ? ', ' + esc(p.audience.toLowerCase()) : ''}): ${esc(p.dek)}</li>`).join('\n');
const contacts = SOCIALS.map(s => `<li><a href="${esc(s.href)}">${esc(s.name)}</a>: ${esc(s.handle)}</li>`).join('\n');
const focusList = `<h2>Focus</h2>\n<ul>\n${FOCUS.map(f => `<li><strong>${esc(f.title)}</strong>: ${esc(f.body)}</li>`).join('\n')}\n</ul>`;
const jobsList = `<h2>Experience</h2>\n${JOBS.map(j => `<h3>${esc(j.role)}, ${esc(j.company)} (${esc(j.date)})</h3>\n<p>${esc(j.context)}</p>${j.points.length ? `\n<ul>\n${j.points.map(pt => `<li>${esc(pt)}</li>`).join('\n')}\n</ul>` : ''}`).join('\n')}`;
const credentialsList = `<h2>Governance &amp; profession</h2>\n<ul>\n${CREDENTIALS.map(c => `<li><strong>${esc(c.title)}</strong>: ${esc(c.detail)}</li>`).join('\n')}\n</ul>`;
const boardSection = `<h2 id="boards">Boards &amp; governance</h2>\n<p>${esc(BOARD.intro)}</p>\n<h3>What I offer a board</h3>\n<ul>\n${BOARD.offers.map(o => `<li>${esc(o)}</li>`).join('\n')}\n</ul>\n<h3>${esc(BOARD.bioLabel)}</h3>\n<p>${esc(BOARD.bio)}</p>`;
const talksList = POSTS.filter(p => p.type === 'Talk').map(p => `<li><a href="/writing/${p.id}/">${esc(p.title)}</a>, ${esc(p.venue || '')}, <time datetime="${p.dt}">${esc(p.date)}</time></li>`).join('\n');
const speakingSection = `<h2 id="speaking">Speaking</h2>\n<p>${esc(SPEAKING.intro)}</p>\n<h3>Topics</h3>\n<ul>\n${SPEAKING.topics.map(t => `<li>${esc(t)}</li>`).join('\n')}\n</ul>\n<h3>Past talks</h3>\n<ul>\n${talksList}\n</ul>\n<h3>Speaker bio</h3>\n<p>${esc(SPEAKING.bio)}</p>`;
const skillsList = `<h2>Skills</h2>\n<dl>\n${SKILLS.map(sk => `<dt>${esc(sk.k)}</dt>\n<dd>${esc(sk.v)}</dd>`).join('\n')}\n</dl>`;

// Home: index.html is the source, so only its marked head and noscript blocks are regenerated in place.
const homeHead = seoHead({ title: HOME_TITLE, ogTitle: 'Matt Kellock', desc: HOME_DESC, path: '/' });
const homeNoscript = `${nav}\n<h1>Matt Kellock</h1>\n<p><strong>${esc(HEADLINE)}</strong></p>\n<p>${esc(TAGLINE)}</p>\n<h2>Talks &amp; writing</h2>\n<ul>\n${listing}\n</ul>\n<h2>About me</h2>\n<p>${esc(HOME_ABOUT)}</p>\n<p><a href="/about/">About Matt Kellock</a> · <a href="/about/#contact">Contact</a></p>\n${focusList}`;
const homeLd = graph();
const newSrc = src
  .replace(/<!-- seo:start -->[\s\S]*?<!-- seo:end -->/, () => `<!-- seo:start -->\n${homeHead}\n<!-- seo:end -->`)
  .replace(/<!-- seo-ld:start -->[\s\S]*?<!-- seo-ld:end -->/, () => `<!-- seo-ld:start -->\n${homeLd}\n<!-- seo-ld:end -->`)
  .replace(/<!-- noscript:start -->[\s\S]*?<!-- noscript:end -->/, () => noscriptSlot(homeNoscript));
if (newSrc !== src) { src = newSrc; write('index.html', src); }

// About
write('about/index.html', render({
  head: seoHead({ title: ABOUT_TITLE, ogTitle: 'About Matt Kellock', desc: ABOUT_DESC, path: '/about/', type: 'profile',
    extra: ['<meta property="profile:first_name" content="Matt">', '<meta property="profile:last_name" content="Kellock">'] }),
  jsonld: graph({ '@type': 'ProfilePage', url: SITE + '/about/', dateModified: isoTime(ABOUT_UPDATED), mainEntity: person, breadcrumb: crumbs([['Home', '/'], ['About', '/about/']]) }),
  noscript: `${nav}\n<h1>About Matt Kellock</h1>\n<p><strong>${esc(HEADLINE)}</strong></p>\n<p>${esc(ABOUT_TAGLINE)}</p>\n<h2>Background</h2>\n${BIO.map(b => `<p>${esc(b)}</p>`).join('\n')}\n${boardSection}\n${jobsList}\n${credentialsList}\n${skillsList}\n${speakingSection}\n<h2 id="contact">Contact &amp; elsewhere</h2>\n<p>${esc(CONTACT_NOTE)}</p>\n<ul>\n${contacts}\n</ul>`
}));

// Writing index
write('writing/index.html', render({
  head: seoHead({ title: WRITING_TITLE, ogTitle: 'Talks & writing by Matt Kellock', desc: WRITING_DESC, path: '/writing/' }),
  jsonld: graph({
    '@type': 'CollectionPage', name: 'Talks & writing', url: SITE + '/writing/', author: person, isPartOf: website,
    hasPart: POSTS.map(p => ({ '@type': 'BlogPosting', headline: p.title, url: `${SITE}/writing/${p.id}/`, datePublished: isoTime(p.dt), dateModified: isoTime(p.updated || p.dt) })),
    breadcrumb: crumbs([['Home', '/'], ['Talks & writing', '/writing/']])
  }),
  noscript: `${nav}\n<h1>Talks &amp; writing</h1>\n<p>${esc(WRITING_INTRO)}</p>\n<ul>\n${listing}\n</ul>\n<p><a href="/feed.xml">RSS feed</a></p>`
}));

// One page per talk or article
const postDirs = new Set(POSTS.map(p => p.id));
const links = p => (p.links || []).length ? `<h2>Elsewhere</h2>\n<ul>\n${p.links.map(l => `<li><a href="${esc(l.href)}">${esc(l.label)}</a> (${esc(l.source)})</li>`).join('\n')}\n</ul>` : '';
const built = [];
for (const p of POSTS) {
  const path = `/writing/${p.id}/`;
  const image = await postImage(p);
  const conv = converted.get(p.id), words = conv.words;
  const pageHtml = tocFor(p, conv), bodyHtml = conv.html;
  // Fragment the app fetches when the article is opened from another page (with the contents list).
  if (p.md) write(`writing/${p.id}/body.html`, pageHtml + '\n');
  const published = isoTime(p.dt), modified = isoTime(p.updated || p.dt);
  built.push({ p, path, image, bodyHtml });
  const companion = p.related && POSTS.find(x => x.id === p.related);
  const header = `${nav}\n${p.md ? '' : '<article>\n'}<p>${esc(p.type)} · <time datetime="${p.dt}">${esc(p.date)}</time>${p.venue ? ' · ' + esc(p.venue) : ''}${p.audience ? ' · ' + esc(p.audience) : ''} · ${readMins(words)} min read</p>\n<h1>${esc(p.title)}</h1>\n<p>${esc(p.dek)}</p>\n<p>By <a href="/about/" rel="author">Matt Kellock</a>${p.updated ? `. Updated <time datetime="${p.updated}">${esc(new Date(isoTime(p.updated)).toLocaleDateString('en-AU', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'Australia/Melbourne' }))}</time>` : ''}</p>${companion ? `\n<p>Companion piece: <a href="/writing/${companion.id}/">${esc(companion.title)}</a></p>` : ''}`;
  write(`writing/${p.id}/index.html`, render({
    head: seoHead({
      title: (p.searchTitle || p.title) + ' · Matt Kellock', ogTitle: p.title, desc: p.dek, path, type: 'article', image,
      extra: [
        `<meta property="article:published_time" content="${published}">`,
        `<meta property="article:modified_time" content="${modified}">`,
        `<meta property="og:updated_time" content="${modified}">`,
        `<meta property="article:author" content="${SITE}/about/">`,
        `<meta property="article:section" content="${esc(p.tag)}">`,
        `<meta property="article:tag" content="${esc(p.tag)}">`,
        // Slack, Discord and others show these as labelled rows in link previews.
        `<meta name="twitter:label1" content="Reading time">`,
        `<meta name="twitter:data1" content="${readMins(words)} min read">`,
        `<meta name="twitter:label2" content="${p.type === 'Talk' ? 'Event' : 'Written by'}">`,
        `<meta name="twitter:data2" content="${esc(p.type === 'Talk' && p.venue ? p.venue : 'Matt Kellock')}">`
      ]
    }),
    jsonld: graph(
        {
          '@type': 'BlogPosting', headline: p.title, description: p.dek, datePublished: published, dateModified: modified,
          inLanguage: 'en-AU', image: imageLd(image), url: SITE + path, mainEntityOfPage: SITE + path, ...(p.series ? {} : { isPartOf: website }),
          articleSection: p.tag, keywords: [p.tag, p.type].join(', '), genre: p.type, author: person, publisher: person,
          wordCount: words, timeRequired: `PT${readMins(words)}M`,
          ...(p.links && p.links.length ? { citation: p.links.map(l => l.href) } : {}),
          ...(p.audience ? { audience: { '@type': 'Audience', audienceType: p.audience } } : {}),
          ...(p.series ? { isPartOf: [website, { '@type': 'CreativeWorkSeries', name: p.series }] } : {}),
          ...(p.venue ? { about: { '@type': 'Event', name: p.venue, startDate: published, location: { '@type': 'Place', name: p.venue }, performer: person } } : {})
        },
        crumbs([['Home', '/'], ['Talks & writing', '/writing/'], [p.title, path]])
    ),
    // Markdown bodies get their own noscript: crawlers without JS read it, and the app reads
    // its text on first load instead of fetching body.html.
    noscript: p.md ? header : `${header}\n${bodyHtml}\n${links(p)}\n</article>`,
    extraBody: p.md ? `<noscript id="mk-body-${p.id}">\n${pageHtml}\n</noscript>\n${links(p) ? `<noscript>\n${links(p)}\n</noscript>\n` : ''}` : ''
  }));
}

// Remove pages for posts that no longer exist.
const wdir = join(ROOT, 'writing');
for (const d of readdirSync(wdir, { withFileTypes: true })) {
  if (d.isDirectory() && !postDirs.has(d.name) && existsSync(join(wdir, d.name, 'index.html'))
      && readFileSync(join(wdir, d.name, 'index.html'), 'utf8').includes(MARK)) {
    rmSync(join(wdir, d.name), { recursive: true });
    console.log('removed', `writing/${d.name}/`);
  }
}

// 404: GitHub Pages serves this for unknown paths; the app falls back to the home view.
write('404.html', render({
  head: seoHead({ title: 'Page not found · Matt Kellock', desc: HOME_DESC, path: '/', robots: 'noindex, follow' }),
  jsonld: graph(),
  noscript: `${nav}\n<h1>Page not found</h1>\n<p>The page you asked for does not exist. Try one of these:</p>\n<ul>\n${listing}\n</ul>\n<p><a href="/about/">About Matt Kellock</a></p>`
}));

// Remove share cards that are no longer referenced (only files this build owns).
if (existsSync(join(ROOT, CARD_DIR))) {
  for (const f of readdirSync(join(ROOT, CARD_DIR))) {
    if (/^[a-z0-9-]+-[0-9a-f]{8}\.png$/.test(f) && !usedCards.has(f)) {
      rmSync(join(ROOT, CARD_DIR, f));
      console.log('removed', `${CARD_DIR}/${f}`);
    }
  }
}

// RSS feed with full content. Relative links become absolute for feed readers.
const absolute = (html, path) => html
  .replace(/<img class="mk-img-light"[^>]*>/g, '')
  .replace(/ <a class="mk-anchor"[^>]*>#<\/a>/g, '')
  .replace(/<div class="mk-callout" role="note">/g, '<blockquote>').replace(/<\/div><!--\/callout-->/g, '</blockquote>')
  .replace(/(href|src)="\/(?!\/)/g, `$1="${SITE}/`)
  .replace(/href="#/g, `href="${SITE}${path}#`);
const cdata = s => `<![CDATA[${s.replace(/]]>/g, ']]]]><![CDATA[>')}]]>`;
const enclosure = image => {
  const rel = image.url.slice(SITE.length);
  const file = join(ROOT, rel);
  if (!existsSync(file) || !image.type) return [];
  const length = statSync(file).size;
  return [`      <enclosure url="${image.url}" length="${length}" type="${image.type}"/>`,
    `      <media:content url="${image.url}" medium="image" type="${image.type}" width="${image.width}" height="${image.height}"/>`];
};
const feedItems = built.map(({ p, path, image, bodyHtml }) => [
  '    <item>',
  `      <title>${esc(p.title)}</title>`,
  `      <link>${SITE}${path}</link>`,
  `      <guid isPermaLink="true">${SITE}${path}</guid>`,
  `      <pubDate>${rfc822(p.dt)}</pubDate>`,
  `      <dc:creator>Matt Kellock</dc:creator>`,
  `      <category>${esc(p.tag)}</category>`,
  `      <description>${esc(p.dek)}</description>`,
  ...enclosure(image),
  `      <content:encoded>${cdata(absolute(`<p><em>${esc(p.dek)}</em></p>\n${bodyHtml}\n${links(p)}`, path))}</content:encoded>`,
  '    </item>'
].join('\n'));
write('feed.xml', [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:media="http://search.yahoo.com/mrss/">',
  '  <channel>',
  '    <title>Matt Kellock: Talks &amp; writing</title>',
  `    <link>${SITE}/writing/</link>`,
  `    <atom:link href="${SITE}/feed.xml" rel="self" type="application/rss+xml"/>`,
  `    <description>${esc(WRITING_DESC)}</description>`,
  '    <language>en-AU</language>',
  POSTS.length ? `    <lastBuildDate>${rfc822(POSTS.map(p => p.updated || p.dt).sort().pop())}</lastBuildDate>` : '',
  ...feedItems,
  '  </channel>',
  '</rss>',
  ''
].filter(Boolean).join('\n'));

// Sitemap, with each page's share image.
const postImages = Object.fromEntries(built.map(b => [b.path, b.image.url]));
const newest = POSTS.map(p => p.updated || p.dt).sort().pop();
const urls = [
  ['/', [newest, ABOUT_UPDATED].sort().pop(), siteCard.url], ['/writing/', newest, siteCard.url], ['/about/', ABOUT_UPDATED, siteCard.url],
  ...POSTS.map(p => [`/writing/${p.id}/`, p.updated || p.dt, postImages[`/writing/${p.id}/`]])
];
write('sitemap.xml', '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n'
  + urls.map(([u, d, img]) => `  <url><loc>${SITE}${u}</loc>${d ? `<lastmod>${d}</lastmod>` : ''}${img ? `<image:image><image:loc>${img}</image:loc></image:image>` : ''}</url>`).join('\n')
  + '\n</urlset>\n');
