// Generates crawlable copies of index.html for each route, plus sitemap.xml.
// Run after any change to index.html:  node scripts/build.mjs
// No dependencies. Content comes from the POSTS array in index.html's x-dc script block;
// posts with `md: true` take their body from posts/<id>.md (see scripts/markdown.mjs).
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';
import { markdownToHtml } from './markdown.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://kellock.com.au';
const IMAGE = SITE + '/images/profile.jpg';
const MARK = '<!-- GENERATED by scripts/build.mjs from index.html. Do not edit; edit index.html and rebuild. -->';

const src = readFileSync(join(ROOT, 'index.html'), 'utf8');

// Evaluate the x-dc script with just enough stubs to read its constants.
const script = src.match(/<script type="text\/x-dc"[^>]*>([\s\S]*?)<\/script>/)[1];
const ctx = { DCLogic: class {}, window: { location: { hash: '', pathname: '/' } }, localStorage: { getItem: () => null, setItem() {} } };
vm.createContext(ctx);
vm.runInContext(script + '\n;globalThis.__out = { POSTS, HOME_DESC, WRITING_DESC, ABOUT_DESC };', ctx);
const { POSTS, HOME_DESC, WRITING_DESC, ABOUT_DESC } = ctx.__out;

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const ld = obj => '<script type="application/ld+json">\n' + JSON.stringify({ '@context': 'https://schema.org', ...obj }, null, 2).replace(/</g, '\\u003c') + '\n</script>';
const person = { '@type': 'Person', '@id': SITE + '/#person', name: 'Matt Kellock', url: SITE + '/' };
const crumbs = items => ({ '@type': 'BreadcrumbList', itemListElement: items.map(([name, path], i) => ({ '@type': 'ListItem', position: i + 1, name, item: SITE + path })) });

function seoHead({ title, desc, path, type = 'website', robots = 'index, follow', image = IMAGE, imageAlt = 'Portrait of Matt Kellock', extra = '' }) {
  const url = SITE + path;
  return [
    `<title>${esc(title)}</title>`,
    `<meta name="description" content="${esc(desc)}">`,
    `<meta name="robots" content="${robots}">`,
    `<link rel="canonical" href="${url}">`,
    `<meta property="og:type" content="${type}">`,
    `<meta property="og:url" content="${url}">`,
    `<meta property="og:title" content="${esc(title)}">`,
    `<meta property="og:description" content="${esc(desc)}">`,
    `<meta name="twitter:title" content="${esc(title)}">`,
    `<meta name="twitter:description" content="${esc(desc)}">`,
    `<meta property="og:image" content="${image}">`,
    `<meta property="og:image:alt" content="${esc(imageAlt)}">`,
    `<meta name="twitter:image" content="${image}">`,
    extra
  ].filter(Boolean).join('\n');
}

function render({ head, jsonld = '', noscript = '', extraBody = '' }) {
  let out = src
    .replace(/<!-- seo:start -->[\s\S]*?<!-- seo:end -->/, `<!-- seo:start -->\n${head}\n<!-- seo:end -->`)
    .replace(/<!-- seo-ld:start -->[\s\S]*?<!-- seo-ld:end -->/, `<!-- seo-ld:start -->${jsonld ? '\n' + jsonld + '\n' : ''}<!-- seo-ld:end -->`)
    .replace(/^<!DOCTYPE html>\n/i, `<!DOCTYPE html>\n${MARK}\n`);
  if (noscript || extraBody) out = out.replace('<body>\n', `<body>\n${noscript ? `<noscript>\n${noscript}\n</noscript>\n` : ''}${extraBody}`);
  return out;
}

function write(rel, html) {
  const file = join(ROOT, rel);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, html);
  console.log('wrote', rel);
}

const nav = `<nav><a href="/">Matt Kellock</a> · <a href="/writing/">Writing</a> · <a href="/about/">About</a></nav>`;
const block = b => b.isH ? `<h2>${esc(b.text)}</h2>` : b.isQ ? `<blockquote>${esc(b.text)}</blockquote>` : `<p>${esc(b.text)}</p>`;
const listing = POSTS.map(p => `<li><a href="/writing/${p.id}/">${esc(p.title)}</a> (${esc(p.type)}, <time datetime="${p.dt}">${esc(p.date)}</time>): ${esc(p.dek)}</li>`).join('\n');

// About
write('about/index.html', render({
  head: seoHead({ title: 'About · Matt Kellock', desc: ABOUT_DESC, path: '/about/', type: 'profile' }),
  jsonld: ld({ '@type': 'ProfilePage', url: SITE + '/about/', mainEntity: person, breadcrumb: crumbs([['Home', '/'], ['About', '/about/']]) }),
  noscript: `${nav}\n<h1>About Matt Kellock</h1>\n<p>${esc(ABOUT_DESC)}</p>`
}));

// Writing index
write('writing/index.html', render({
  head: seoHead({ title: 'Talks & writing · Matt Kellock', desc: WRITING_DESC, path: '/writing/' }),
  jsonld: ld({
    '@type': 'CollectionPage', name: 'Talks & writing', url: SITE + '/writing/', author: person,
    hasPart: POSTS.map(p => ({ '@type': 'Article', headline: p.title, url: `${SITE}/writing/${p.id}/`, datePublished: p.dt })),
    breadcrumb: crumbs([['Home', '/'], ['Talks & writing', '/writing/']])
  }),
  noscript: `${nav}\n<h1>Talks &amp; writing</h1>\n<ul>\n${listing}\n</ul>`
}));

// One page per talk or article
const postDirs = new Set(POSTS.map(p => p.id));
const links = p => (p.links || []).length ? `<h2>Elsewhere</h2>\n<ul>\n${p.links.map(l => `<li><a href="${esc(l.href)}">${esc(l.label)}</a> (${esc(l.source)})</li>`).join('\n')}\n</ul>` : '';
for (const p of POSTS) {
  const path = `/writing/${p.id}/`;
  const image = p.image ? SITE + p.image : IMAGE;
  let bodyHtml, words;
  if (p.md) {
    ({ html: bodyHtml, words } = markdownToHtml(readFileSync(join(ROOT, 'posts', p.id + '.md'), 'utf8'), p.id));
    // Fragment the app fetches when the article is opened from another page.
    write(`writing/${p.id}/body.html`, bodyHtml + '\n');
  } else {
    bodyHtml = p.body.map(block).join('\n');
  }
  const header = `${nav}\n${p.md ? '' : '<article>\n'}<p>${esc(p.type)} · <time datetime="${p.dt}">${esc(p.date)}</time>${p.venue ? ' · ' + esc(p.venue) : ''}</p>\n<h1>${esc(p.title)}</h1>\n<p>${esc(p.dek)}</p>`;
  write(`writing/${p.id}/index.html`, render({
    head: seoHead({
      title: p.title + ' · Matt Kellock', desc: p.dek, path, type: 'article',
      ...(p.image ? { image, imageAlt: p.imageAlt || p.title } : {}),
      extra: [
        `<meta property="article:published_time" content="${p.dt}">`,
        `<meta property="article:author" content="${SITE}/about/">`,
        `<meta property="article:section" content="${esc(p.tag)}">`
      ].join('\n')
    }),
    jsonld: ld({
      '@graph': [
        {
          '@type': 'Article', headline: p.title, description: p.dek, datePublished: p.dt, dateModified: p.updated || p.dt,
          inLanguage: 'en-AU', image, url: SITE + path, mainEntityOfPage: SITE + path,
          articleSection: p.tag, genre: p.type, author: person, publisher: person,
          ...(words ? { wordCount: words } : {}),
          ...(p.links && p.links.length ? { citation: p.links.map(l => l.href) } : {}),
          ...(p.venue ? { locationCreated: { '@type': 'Place', name: p.venue } } : {})
        },
        crumbs([['Home', '/'], ['Talks & writing', '/writing/'], [p.title, path]])
      ]
    }),
    // Markdown bodies get their own noscript: crawlers without JS read it, and the app reads
    // its text on first load instead of fetching body.html.
    noscript: p.md ? header : `${header}\n${bodyHtml}\n${links(p)}\n</article>`,
    extraBody: p.md ? `<noscript id="mk-body-${p.id}">\n${bodyHtml}\n</noscript>\n${links(p) ? `<noscript>\n${links(p)}\n</noscript>\n` : ''}` : ''
  }));
}

// Remove pages for posts that no longer exist.
const wdir = join(ROOT, 'writing');
for (const d of readdirSync(wdir, { withFileTypes: true })) {
  if (d.isDirectory() && !postDirs.has(d.name) && existsSync(join(wdir, d.name, 'index.html'))
      && readFileSync(join(wdir, d.name, 'index.html'), 'utf8').includes(MARK)) {
    rmSync(join(wdir, d.name), { recursive: true });
    console.log('removed', `writing/${d.name}/`);
  }
}

// 404: GitHub Pages serves this for unknown paths; the app falls back to the home view.
write('404.html', render({
  head: seoHead({ title: 'Page not found · Matt Kellock', desc: HOME_DESC, path: '/', robots: 'noindex, follow' }),
  noscript: `${nav}\n<h1>Page not found</h1>`
}));

// Sitemap
const urls = [
  ['/', POSTS[0]?.dt], ['/writing/', POSTS[0]?.dt], ['/about/', null],
  ...POSTS.map(p => [`/writing/${p.id}/`, p.updated || p.dt])
];
write('sitemap.xml', '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
  + urls.map(([u, d]) => `  <url><loc>${SITE}${u}</loc>${d ? `<lastmod>${d}</lastmod>` : ''}</url>`).join('\n')
  + '\n</urlset>\n');
